### ISSUE TITLE
Process for contributing data integration sources and sinks

### ISSUE THREAD

**Issue by ghost** [nstack/nstack#11]
Hello there,

I find this project very exciting. It would be great if you could make it clear how to contribute new data integration sources and sinks. In our case that'd be Apache Kafka and Microsoft SQL Server.

**Comment by mands** [comment]
Hi there - thanks for your kind words!

At the moment the available sources and sinks are hardcoded, however we're actively working introducing support for creating your own sources and sinks within any of the supported integration languages - this work is complete and should land within the next few weeks.

Kafka support in particular in high on the roadmap and something we'd love to get working soon!

I'll update this issue when it goes live - cheers!

**Comment by optiomas** [comment]
Great! Looking forward to contribute.
